export const tempNotificationData = [
  {
    src: `${process.env.NEXT_PUBLIC_FRONT}`,
    image: '/images/temp/profile.png',
    nickname: '닉네임',
    ttabName: '탭이름',
    date: '2024.03.01',
    requestJoin: true,
    unchecked: true,
  },
  {
    src: `${process.env.NEXT_PUBLIC_FRONT}`,
    image: '/images/temp/profile.png',
    nickname: 'vaiv',
    ttabName: '탭이름2',
    date: '2024.02.01',
    like: true,
  },
  {
    src: `${process.env.NEXT_PUBLIC_FRONT}`,
    image: '/images/temp/profile.png',
    nickname: 'ABCDEFG',
    ttabName: '탭이름',
    date: '2024.01.01',
    comment: true,
    unchecked: true,
  },
  {
    src: `${process.env.NEXT_PUBLIC_FRONT}`,
    image: '/images/temp/profile.png',
    nickname: '닉네임',
    ttabName: '탭이름',
    date: '2024.01.01',
    report: true,
  },
  {
    src: `${process.env.NEXT_PUBLIC_FRONT}`,
    image: '/images/temp/profile.png',
    nickname: '닉네임',
    ttabName: '탭이름',
    date: '2024.01.01',
    requestJoin: true,
  },
];